spring.application.name=SmartExpenseTracker

spring.datasource.url=jdbc:postgresql://localhost:5433/smart_expense_tracker
spring.datasource.username=imprint
spring.datasource.password=olamideeh

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true